// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/maktab-fonts/Current.tsx": () => import("../components/mockups/maktab-fonts/Current.tsx"),
  "./components/mockups/maktab-fonts/Lato.tsx": () => import("../components/mockups/maktab-fonts/Lato.tsx"),
  "./components/mockups/maktab-fonts/NunitoSans.tsx": () => import("../components/mockups/maktab-fonts/NunitoSans.tsx")
};
